UPDATES_TIMEOUT_SEC = 10
HISTORY_WRITE_TIMEOUT_H = 12  # NEED FIX ALL THIS SYS

CHAIN_EQ_CHECK = 10


# percent step. when need call emergency notification
COST_NOTIFY_STEP = 5
VOLUME_NOTIFY_STEP = 30
